---
- hosts: 127.0.0.1
  user: vagrant
  gather_facts: false
  tasks:
    - name: "wget"
      apt: pkg=wget
      sudo: yes
    - action: command wget -q "https://ftp.orca.med.or.jp/pub/ubuntu/archive.key"
      sudo: yes
    - action: command apt-key add archive.key
      sudo: yes
    - action: command wget -q -O /etc/apt/sources.list.d/jma-receipt-trusty48.list "https://ftp.orca.med.or.jp/pub/ubuntu/jma-receipt-trusty48.list"
      sudo: yes
    - name: "apt-get update"
      apt: update_cache=yes
      sudo: yes
    - name: "apt-get install -y jma-receipt"
      apt: pkg=jma-receipt
      sudo: yes
    - action: command wget "https://ftp.orca.med.or.jp/pub/data/receipt/outline/update/claim_update.tar.gz"
    - name: "tar xzvf"
      unarchive: src=./claim_update.tar.gz dest=./
    - shell: /bin/bash claim_update.sh
      sudo: yes
    - shell: service postgresql restart
      sudo: yes
    - shell: jma-setup
      sudo: yes
    - shell: service jma-receipt start
      sudo: yes
#    - action: command echo -e "ormaster123\normaster123\n" | sudo -u orca /usr/lib/jma-receipt/bin/passwd_store.sh
